---
abstract: 'Multicast DNS in AnyEvent style'
author:
  - 'Tatsuhiko Miyagawa <miyagawa@bulknews.net>'
build_requires:
  ExtUtils::MakeMaker: 6.59
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.59
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.06'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: AnyEvent-mDNS
no_index:
  directory:
    - inc
    - t
    - xt
requires:
  AnyEvent: 7
  AnyEvent::Handle::UDP: 0.038
  perl: 5.8.1
resources:
  license: http://dev.perl.org/licenses/
  repository: git://github.com/miyagawa/AnyEvent-mDNS.git
version: 0.06
